"""empty message

Revision ID: ac5ee64863de
Revises: 3588a2f703d9
Create Date: 2020-11-10 19:23:56.903489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5ee64863de'
down_revision = '3588a2f703d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_author_id'), 'post', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_posted_at'), 'post', ['posted_at'], unique=False)
    op.drop_index('ix_posts_posted_at', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=32), nullable=True),
    sa.Column('title', sa.VARCHAR(length=32), nullable=True),
    sa.Column('content', sa.VARCHAR(length=256), nullable=False),
    sa.Column('posted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_posted_at', 'posts', ['posted_at'], unique=False)
    op.drop_index(op.f('ix_post_posted_at'), table_name='post')
    op.drop_index(op.f('ix_post_author_id'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
